package com.google.android.gms.games.internal.player;

import android.text.TextUtils;

public final class zze {
    public final String name;
    public final String title;
    public final String zzick;
    public final String zzicl;
    public final String zzicm;
    public final String zzicn;
    public final String zzico;
    public final String zzicp;
    public final String zzicq;
    public final String zzicr;
    public final String zzics;
    public final String zzict;
    public final String zzicu;
    public final String zzicv;
    public final String zzicw;
    public final String zzicx;
    public final String zzicy;
    public final String zzicz;
    private String zzida;
    public final String zzidb;
    public final String zzidc;
    public final String zzidd;
    public final String zzide;
    public final String zzidf;
    public final String zzidg;
    public final String zzidh;
    public final String zzidi;
    public final String zzidj;
    public final String zzidk;
    public final String zzidl;
    public final String zzidm;
    public final String zzidn;
    public final String zzido;
    public final String zzidp;
    public final String zzidq;

    public zze(String str) {
        String str2;
        String str3 = "most_recent_activity_timestamp";
        String str4 = "most_recent_game_name";
        String str5 = "most_recent_external_game_id";
        String str6 = "is_profile_visible";
        String str7 = "has_all_public_acls";
        String str8 = "player_title";
        String str9 = "last_level_up_timestamp";
        String str10 = "next_level_max_xp";
        if (TextUtils.isEmpty(str)) {
            this.zzick = "external_player_id";
            this.zzicl = "profile_name";
            this.zzicm = "profile_icon_image_uri";
            this.zzicn = "profile_icon_image_url";
            this.zzico = "profile_hi_res_image_uri";
            this.zzicp = "profile_hi_res_image_url";
            this.zzicq = "last_updated";
            this.zzicr = "is_in_circles";
            this.zzics = "played_with_timestamp";
            this.zzict = "current_xp_total";
            this.zzicu = "current_level";
            this.zzicv = "current_level_min_xp";
            this.zzicw = "current_level_max_xp";
            this.zzicx = "next_level";
            this.zzicy = str10;
            this.zzicz = str9;
            this.title = str8;
            this.zzida = str7;
            this.zzidb = str6;
            this.zzidc = str5;
            this.zzidd = str4;
            this.zzide = str3;
            this.zzidf = "most_recent_game_icon_uri";
            this.zzidg = "most_recent_game_hi_res_uri";
            this.zzidh = "most_recent_game_featured_uri";
            this.zzidi = "has_debug_access";
            this.zzidj = "gamer_tag";
            this.name = "real_name";
            this.zzidk = "banner_image_landscape_uri";
            this.zzidl = "banner_image_landscape_url";
            this.zzidm = "banner_image_portrait_uri";
            this.zzidn = "banner_image_portrait_url";
            this.zzido = "gamer_friend_status";
            this.zzidp = "gamer_friend_update_timestamp";
            str2 = "is_muted";
        } else {
            String valueOf = String.valueOf(str);
            this.zzick = "external_player_id".length() != 0 ? valueOf.concat("external_player_id") : new String(valueOf);
            String valueOf2 = String.valueOf(str);
            this.zzicl = "profile_name".length() != 0 ? valueOf2.concat("profile_name") : new String(valueOf2);
            String valueOf3 = String.valueOf(str);
            this.zzicm = "profile_icon_image_uri".length() != 0 ? valueOf3.concat("profile_icon_image_uri") : new String(valueOf3);
            String valueOf4 = String.valueOf(str);
            this.zzicn = "profile_icon_image_url".length() != 0 ? valueOf4.concat("profile_icon_image_url") : new String(valueOf4);
            String valueOf5 = String.valueOf(str);
            this.zzico = "profile_hi_res_image_uri".length() != 0 ? valueOf5.concat("profile_hi_res_image_uri") : new String(valueOf5);
            String valueOf6 = String.valueOf(str);
            this.zzicp = "profile_hi_res_image_url".length() != 0 ? valueOf6.concat("profile_hi_res_image_url") : new String(valueOf6);
            String valueOf7 = String.valueOf(str);
            this.zzicq = "last_updated".length() != 0 ? valueOf7.concat("last_updated") : new String(valueOf7);
            String valueOf8 = String.valueOf(str);
            this.zzicr = "is_in_circles".length() != 0 ? valueOf8.concat("is_in_circles") : new String(valueOf8);
            String valueOf9 = String.valueOf(str);
            this.zzics = "played_with_timestamp".length() != 0 ? valueOf9.concat("played_with_timestamp") : new String(valueOf9);
            String valueOf10 = String.valueOf(str);
            this.zzict = "current_xp_total".length() != 0 ? valueOf10.concat("current_xp_total") : new String(valueOf10);
            String valueOf11 = String.valueOf(str);
            this.zzicu = "current_level".length() != 0 ? valueOf11.concat("current_level") : new String(valueOf11);
            String valueOf12 = String.valueOf(str);
            this.zzicv = "current_level_min_xp".length() != 0 ? valueOf12.concat("current_level_min_xp") : new String(valueOf12);
            String valueOf13 = String.valueOf(str);
            this.zzicw = "current_level_max_xp".length() != 0 ? valueOf13.concat("current_level_max_xp") : new String(valueOf13);
            String valueOf14 = String.valueOf(str);
            this.zzicx = "next_level".length() != 0 ? valueOf14.concat("next_level") : new String(valueOf14);
            String valueOf15 = String.valueOf(str);
            this.zzicy = str10.length() != 0 ? valueOf15.concat(str10) : new String(valueOf15);
            String valueOf16 = String.valueOf(str);
            this.zzicz = str9.length() != 0 ? valueOf16.concat(str9) : new String(valueOf16);
            String valueOf17 = String.valueOf(str);
            this.title = str8.length() != 0 ? valueOf17.concat(str8) : new String(valueOf17);
            String valueOf18 = String.valueOf(str);
            this.zzida = str7.length() != 0 ? valueOf18.concat(str7) : new String(valueOf18);
            String valueOf19 = String.valueOf(str);
            this.zzidb = str6.length() != 0 ? valueOf19.concat(str6) : new String(valueOf19);
            String valueOf20 = String.valueOf(str);
            this.zzidc = str5.length() != 0 ? valueOf20.concat(str5) : new String(valueOf20);
            String valueOf21 = String.valueOf(str);
            this.zzidd = str4.length() != 0 ? valueOf21.concat(str4) : new String(valueOf21);
            String valueOf22 = String.valueOf(str);
            this.zzide = str3.length() != 0 ? valueOf22.concat(str3) : new String(valueOf22);
            String valueOf23 = String.valueOf(str);
            this.zzidf = "most_recent_game_icon_uri".length() != 0 ? valueOf23.concat("most_recent_game_icon_uri") : new String(valueOf23);
            String valueOf24 = String.valueOf(str);
            this.zzidg = "most_recent_game_hi_res_uri".length() != 0 ? valueOf24.concat("most_recent_game_hi_res_uri") : new String(valueOf24);
            String valueOf25 = String.valueOf(str);
            this.zzidh = "most_recent_game_featured_uri".length() != 0 ? valueOf25.concat("most_recent_game_featured_uri") : new String(valueOf25);
            String valueOf26 = String.valueOf(str);
            this.zzidi = "has_debug_access".length() != 0 ? valueOf26.concat("has_debug_access") : new String(valueOf26);
            String valueOf27 = String.valueOf(str);
            this.zzidj = "gamer_tag".length() != 0 ? valueOf27.concat("gamer_tag") : new String(valueOf27);
            String valueOf28 = String.valueOf(str);
            this.name = "real_name".length() != 0 ? valueOf28.concat("real_name") : new String(valueOf28);
            String valueOf29 = String.valueOf(str);
            this.zzidk = "banner_image_landscape_uri".length() != 0 ? valueOf29.concat("banner_image_landscape_uri") : new String(valueOf29);
            String valueOf30 = String.valueOf(str);
            this.zzidl = "banner_image_landscape_url".length() != 0 ? valueOf30.concat("banner_image_landscape_url") : new String(valueOf30);
            String valueOf31 = String.valueOf(str);
            this.zzidm = "banner_image_portrait_uri".length() != 0 ? valueOf31.concat("banner_image_portrait_uri") : new String(valueOf31);
            String valueOf32 = String.valueOf(str);
            this.zzidn = "banner_image_portrait_url".length() != 0 ? valueOf32.concat("banner_image_portrait_url") : new String(valueOf32);
            String valueOf33 = String.valueOf(str);
            this.zzido = "gamer_friend_status".length() != 0 ? valueOf33.concat("gamer_friend_status") : new String(valueOf33);
            String valueOf34 = String.valueOf(str);
            this.zzidp = "gamer_friend_update_timestamp".length() != 0 ? valueOf34.concat("gamer_friend_update_timestamp") : new String(valueOf34);
            String valueOf35 = String.valueOf(str);
            str2 = "is_muted".length() != 0 ? valueOf35.concat("is_muted") : new String(valueOf35);
        }
        this.zzidq = str2;
    }
}
