package com.google.android.gms.internal;

import com.google.android.gms.common.data.BitmapTeleporter;
import com.google.android.gms.drive.DriveId;
import com.google.android.gms.drive.metadata.MetadataField;
import com.google.android.gms.drive.metadata.internal.zzb;
import com.google.android.gms.drive.metadata.internal.zzi;
import com.google.android.gms.drive.metadata.internal.zzo;
import com.google.android.gms.drive.metadata.internal.zzs;
import com.google.android.gms.drive.metadata.internal.zzt;
import com.google.android.gms.drive.metadata.internal.zzu;
import com.google.android.gms.plus.PlusShare;
import java.util.Collections;

public final class zzbuj {
    public static final MetadataField<DriveId> zzgyx = zzbvd.zzhav;
    public static final MetadataField<String> zzgyy = new zzt("alternateLink", 4300000);
    public static final zzbum zzgyz = new zzbum(5000000);
    public static final MetadataField<String> zzgza = new zzt(PlusShare.KEY_CONTENT_DEEP_LINK_METADATA_DESCRIPTION, 4300000);
    public static final MetadataField<String> zzgzb = new zzt("embedLink", 4300000);
    public static final MetadataField<String> zzgzc = new zzt("fileExtension", 4300000);
    public static final MetadataField<Long> zzgzd = new zzi("fileSize", 4300000);
    public static final MetadataField<String> zzgze = new zzt("folderColorRgb", 7500000);
    public static final MetadataField<Boolean> zzgzf = new zzb("hasThumbnail", 4300000);
    public static final MetadataField<String> zzgzg = new zzt("indexableText", 4300000);
    public static final MetadataField<Boolean> zzgzh = new zzb("isAppData", 4300000);
    public static final MetadataField<Boolean> zzgzi = new zzb("isCopyable", 4300000);
    public static final MetadataField<Boolean> zzgzj = new zzb("isEditable", 4100000);
    public static final MetadataField<Boolean> zzgzk = new zzbuk("isExplicitlyTrashed", Collections.singleton("trashed"), Collections.emptySet(), 7000000);
    public static final MetadataField<Boolean> zzgzl = new zzb("isLocalContentUpToDate", 7800000);
    public static final zzbun zzgzm = new zzbun("isPinned", 4100000);
    public static final MetadataField<Boolean> zzgzn = new zzb("isOpenable", 7200000);
    public static final MetadataField<Boolean> zzgzo = new zzb("isRestricted", 4300000);
    public static final MetadataField<Boolean> zzgzp = new zzb("isShared", 4300000);
    public static final MetadataField<Boolean> zzgzq = new zzb("isGooglePhotosFolder", 7000000);
    public static final MetadataField<Boolean> zzgzr = new zzb("isGooglePhotosRootFolder", 7000000);
    public static final MetadataField<Boolean> zzgzs = new zzb("isTrashable", 4400000);
    public static final MetadataField<Boolean> zzgzt = new zzb("isViewed", 4300000);
    public static final zzbuo zzgzu = new zzbuo(4100000);
    public static final MetadataField<String> zzgzv = new zzt("originalFilename", 4300000);
    public static final com.google.android.gms.drive.metadata.zzb<String> zzgzw = new zzs("ownerNames", 4300000);
    public static final zzu zzgzx = new zzu("lastModifyingUser", 6000000);
    public static final zzu zzgzy = new zzu("sharingUser", 6000000);
    public static final zzo zzgzz = new zzo(4100000);
    public static final zzbup zzhaa = new zzbup("quotaBytesUsed", 4300000);
    public static final zzbur zzhab = new zzbur("starred", 4100000);
    public static final MetadataField<BitmapTeleporter> zzhac = new zzbul("thumbnail", Collections.emptySet(), Collections.emptySet(), 4400000);
    public static final zzbus zzhad = new zzbus(PlusShare.KEY_CONTENT_DEEP_LINK_METADATA_TITLE, 4100000);
    public static final zzbut zzhae = new zzbut("trashed", 4100000);
    public static final MetadataField<String> zzhaf = new zzt("webContentLink", 4300000);
    public static final MetadataField<String> zzhag = new zzt("webViewLink", 4300000);
    public static final MetadataField<String> zzhah = new zzt("uniqueIdentifier", 5000000);
    public static final zzb zzhai = new zzb("writersCanShare", 6000000);
    public static final MetadataField<String> zzhaj = new zzt("role", 6000000);
    public static final MetadataField<String> zzhak = new zzt("md5Checksum", 7000000);
    public static final zzbuq zzhal = new zzbuq(7000000);
    public static final MetadataField<String> zzham = new zzt("recencyReason", 8000000);
    public static final MetadataField<Boolean> zzhan = new zzb("subscribed", 8000000);
}
